---
- name: Copy file and remove it
  hosts: docker

  vars: 
    src: "hosts.txt"
    dest: "/home/{{ ansible_user }}/{{ src }}"

  tasks:
  
  - name: Copy file to destination host
    ansible.builtin.copy:
      src: "{{ src }}"
      dest: "{{ dest }}"

  - name: Read destination file
    ansible.builtin.shell: 
      cmd: "cat {{ dest }}"
      executable: /bin/bash
    register: output
  
  - name: Destination file contains
    debug:
      var: output.stdout_lines

  - name: Remove file
    ansible.builtin.file:
      path: "{{ dest }}"
      state: absent
