---
- name: Creating user with home dir
  hosts: docker

  tasks:

  - name: Create user 
    ansible.builtin.user:
      name: "{{ docker_user }}"
      state: present
      create_home: true
    become: true

  - name: Check creation
    ansible.builtin.shell: 
      cmd: "cat /etc/passwd | grep {{ docker_user }}; echo ------;ls /home"
      executable: /bin/bash
    register: output
  
  - name: Result is...
    debug:
      var: output.stdout_lines